language: r
cache:
  packages: yes
  directories:
    - $HOME/cache
sudo: false
pandoc_version: 1.19.2.1

install:
  - R -e 'devtools::install(dependencies = TRUE)'

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - R CMD build .
  - R CMD check *tar.gz && ./_build.sh && ./_deploy.sh
