language: r
os:
  - linux
  - osx

cache:
  packages: yes
sudo: false
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install phantomJS; fi

script:
  - R CMD build .
  - R CMD INSTALL *tar.gz
  - if [ $TRAVIS_OS_NAME = osx ]; then R CMD check *tar.gz ; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then R CMD check *tar.gz; if [[ $TRAVIS_COMMIT_MESSAGE != *"[nobook]"* ]]; then ./_build.sh && ./_deploy.sh; fi; fi
