language: r
cache:
  packages: yes
  directories:
    - $HOME/cache
sudo: false
pandoc_version: 1.19.2.1

before_install:
  - Rscript -e 'install.packages(c("tidyverse", "reshape2","Ecdat"));if (!all(c("tidyverse", "reshape2","Ecdat") %in% installed.packages())) { q(status = 1, save = "no")}'

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
