language: r
cache: packages
pandoc_version: 1.19.2.1
r_packages:
  dplyr
  ggplot2
  reshape2

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
