language: r
cache:
  packages: yes
  directories:
    - $HOME/cache
sudo: false
pandoc_version: 1.19.2.1

before_install:
  - chmod +x ./_install.sh
  - ./_install.sh

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
